
teracy-dev:
  # teracy-dev location specification
  location:
    git:
      remote:
        origin: https://github.com/teracyhq/dev.git
      branch: v0.6.0-a5
    sync: true

  # teracy-dev-entry auto update
  entry_location:
    git:
      remote:
        origin: https://github.com/teracyhq-incubator/teracy-dev-entry-v05.git
      branch: master
    sync: true

  extensions:
    - _id: "entry-essential"
      path:
        extension: teracy-dev-essential
      location:
        git:
          remote:
            origin: https://github.com/teracyhq-incubator/teracy-dev-essential.git
          branch: v0.2.0
      require_version: ">= 0.2.0"
      enabled: true

    - _id: "entry-v05-compat"
      path:
        extension: teracy-dev-v05-compat
      location:
        git:
          remote:
            origin: https://github.com/teracyhq-incubator/teracy-dev-v05-compat.git
          branch: v0.1.0
      require_version: ">= 0.1.0"
      enabled: true
