teracy-dev:
  entry_location:
    sync: false


  # extensions:
    # - _id: "entry-1"
    #   path:
    #     lookup: workspace
    #   location:
    #     git: git@github.com:hoatle/teracy-dev-v05-compat.git
    #     branch: develop
    #   require_version: ">= 0.1.0-SNAPSHOT"
    #   enabled: true
